// Gerado por prisma/gen-catalog.ts - nao editar manualmente
export interface CatalogExercise {
  name: string;
  muscleGroup: string;
  gifUrl: string;
  description: string;
}

export const CATALOG: CatalogExercise[] = [
  { name: "Supino Reto com Halteres", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/SpYC0Kp.gif", description: "Alcance maior e estabilidade natural" },
  { name: "Supino Inclinado com Barra", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/3TZduzM.gif", description: "Foco no peito superior" },
  { name: "Supino Declinado com Barra", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/GrO65fd.gif", description: "Foco no peito inferior" },
  { name: "Crossover na Polia", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/0CXGHya.gif", description: "Tensao constante no peitoral" },
  { name: "Voador Inclinado na Polia", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/tBWXbIT.gif", description: "Crucifixo inclinado no cabo" },
  { name: "Supino Maquina Sentado", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/nIR4Rwl.gif", description: "Press de peito guiado" },
  { name: "Pullover com Halter", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/9XjtHvS.gif", description: "Expansao do torax" },
  { name: "Mergulho no Paralelo (Peito)", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/PAgTVaK.gif", description: "Peitoral e triceps com peso corporal" },
  { name: "Flexao Profunda", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/vptOQ4N.gif", description: "Flexao com maior amplitude" },
  { name: "Flexao com Aplauso", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/wigSg76.gif", description: "Flexao explosiva" },
  { name: "Flexao Arqueiro", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/A9qxk2F.gif", description: "Flexao unilateral avancada" },
  { name: "Flexao Declinada", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/i5cEhka.gif", description: "Flexao com pes elevados" },
  { name: "Crucifixo Inclinado com Halteres", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/ESOd5Pl.gif", description: "Foco no peito superior" },
  { name: "Crucifixo Declinado com Halteres", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/xXm4nYq.gif", description: "Foco no peito inferior" },
  { name: "Crossover Baixo na Polia", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/FVmZVhk.gif", description: "Crucifixo baixo com tensao" },
  { name: "Supino Reto Pegada Aberta", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/JsKq9so.gif", description: "Enfase no recrutamento do peitoral" },
  { name: "Chin-up (Pegada Supinada)", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/G70mEAJ.gif", description: "Barra fixa pegada supinada" },
  { name: "Remada Baixa na Polia", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/fUBheHs.gif", description: "Trabalho de dorsal e biceps" },
  { name: "Remada Unilateral com Halter", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/C0MA9bC.gif", description: "Correcao de assimetrias" },
  { name: "Remada Curvada com Halteres", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/BJ0Hz5L.gif", description: "Espessura dorsal bilateral" },
  { name: "Remada Pendlay", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/r0z6xzQ.gif", description: "Remada de potencia" },
  { name: "Pulldown Pro na Polia", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/qdRxqCj.gif", description: "Lat pulldown com barra pro" },
  { name: "Encolhimento (Shrug)", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/dG7tG5y.gif", description: "Trapezio superior" },
  { name: "Pullover Reto na Polia", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/x69MAlq.gif", description: "Lombar e dorsal em extensao" },
  { name: "Remada Rotacional Palmar", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/wt6rwjk.gif", description: "Remada com rotacao do punho" },
  { name: "Pulldown Amplitude Total", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/LEprlgG.gif", description: "Puxada com amplitude completa" },
  { name: "Remada em Pe (Corpo Livre)", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/wd4ds3s.gif", description: "Remada invertida em pe" },
  { name: "Remada no Cabo Unilateral", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/EIsE3u8.gif", description: "Remada alta unilateral" },
  { name: "Encolhimento no Cabo", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/Eg98Ft9.gif", description: "Encolhimento de trapezio no cabo" },
  { name: "Pulldown Atras do Pescoço", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/CmEr4pM.gif", description: "Pulldown largo atras do pescoço" },
  { name: "Desenvolvimento Militar", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/wdRZISl.gif", description: "Press militar com barra" },
  { name: "Desenvolvimento Arnold", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/Xy4jlWA.gif", description: "Rotacao no desenvolvimento" },
  { name: "Desenvolvimento Sentado com Halteres", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/znQUdHY.gif", description: "Deltoide anterior e lateral" },
  { name: "Elevacao Frontal com Barra", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/b2Uoz54.gif", description: "Deltoide anterior" },
  { name: "Elevacao Frontal com Halteres", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/3eGE2JC.gif", description: "Deltoide anterior" },
  { name: "Elevacao Lateral Unilateral na Polia", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/wEulIzp.gif", description: "Deltoide lateral com tensao constante" },
  { name: "Elevacao Posterior Curvado", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/vYk8lqw.gif", description: "Deltoide posterior" },
  { name: "Elevacao Posterior com Barra", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/Ln9iTbU.gif", description: "Posterior de ombro em pe" },
  { name: "Crucifixo Invertido Cruzado", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/aqvSOQE.gif", description: "Posterior de ombro na polia" },
  { name: "Remada Alta", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/UDlhcO8.gif", description: "Trapezio e deltoide lateral" },
  { name: "Press Cubano", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/QfAKy1G.gif", description: "Rotadores externos e press" },
  { name: "Push Press com Halteres", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/FS63wTN.gif", description: "Press com impulso de pernas" },
  { name: "Arranco Unilateral", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/xHKN2s8.gif", description: "Arranco com um braco" },
  { name: "Rosca Alternada com Barra", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/Yza7XrQ.gif", description: "Biceps alternado" },
  { name: "Rosca Direta no Cabo", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/BCGQ6J5.gif", description: "Curl neutro no cabo" },
  { name: "Rosca Martelo na Corda", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/HPlPoQA.gif", description: "Biceps e braquial" },
  { name: "Rosca Scott com Barra", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/qOgPVf6.gif", description: "Isolamento do biceps" },
  { name: "Rosca Scott no Cabo", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/P2lNrGL.gif", description: "Scott com tensao constante" },
  { name: "Rosca Concentrada no Cabo", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/NvfE43H.gif", description: "Biceps com apoio" },
  { name: "Rosca Inversa", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/xNrS20v.gif", description: "Braquiorradial e antebraco" },
  { name: "Rosca Inclinada Pronada", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/WLvTAv5.gif", description: "Alongamento e peak do biceps" },
  { name: "Triceps na Polia (Corda)", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/dU605di.gif", description: "Triceps com corda" },
  { name: "Triceps na Polia (Barra)", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/3ZflifB.gif", description: "Pushdown tradicional" },
  { name: "Triceps Coice na Polia", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/HEJ6DIX.gif", description: "Kickback com tensao constante" },
  { name: "Francês deitado", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/iZop9xO.gif", description: "Triceps deitado com barra" },
  { name: "Skull Crusher", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/h8LFzo9.gif", description: "Triceps com barra na testa" },
  { name: "Triceps acima da Cabeça na Polia", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/1xHyxys.gif", description: "Extensao acima da cabeca no cabo" },
  { name: "Mergulho no Banco", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/RrLske5.gif", description: "Triceps com peso corporal" },
  { name: "Triceps Unilateral na Polia", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/qRZ5S1N.gif", description: "Pushdown unilateral" },
  { name: "Agachamento Frontal", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/zG0zs85.gif", description: "Quadriceps com carga frontal" },
  { name: "Agachamento com Barra Baixa", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/bTpEUcm.gif", description: "Padrao posterior de agachamento" },
  { name: "Agachamento Afastado", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/s7HX1BY.gif", description: "Agachamento com base larga" },
  { name: "Afundo Bulgaro com Barra", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/gGNQmVt.gif", description: "Trabalho unilateral" },
  { name: "Hack Squat", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/5VCj6iH.gif", description: "Quadriceps com barra atras" },
  { name: "Zercher Squat", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/LSTChY9.gif", description: "Agachamento com barra nos bracos" },
  { name: "Good Morning", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/XlZ4lAC.gif", description: "Posterior e lombar" },
  { name: "Levantamento Terra", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/ila4NZS.gif", description: "Cadeia posterior completa" },
  { name: "Levantamento Terra Sumo", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/KgI0tqW.gif", description: "Terra com pegada larga" },
  { name: "RDL (Romano)", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/wQ2c4XD.gif", description: "Posterior de coxa enfase" },
  { name: "Afundo com Barra", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/t8iSghb.gif", description: "Estabilidade de pernas e equilibrio" },
  { name: "Afundo com Halteres", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/RRWFUcw.gif", description: "Afundo com carga lateral" },
  { name: "Glute Bridge com Barra", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/qKBpF7I.gif", description: "Gluteos com barra" },
  { name: "Hip Thrust", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/qg2PGl6.gif", description: "Elevacao pelvica no banco" },
  { name: "Panturrilha em Pe", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/8ozhUIZ.gif", description: "Gastrocnemio em pe" },
  { name: "Panturrilha Sentada", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/ktsFQAZ.gif", description: "Solet e gastrocnemio" },
  { name: "Panturrilha Unilateral", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/1kB3Wmk.gif", description: "Panturrilha unilateral" },
  { name: "Step-up com Barra", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/Kxquu2E.gif", description: "Subida em caixa com carga" },
  { name: "Agachamento com Salto", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/1gFNTZV.gif", description: "Potencia de pernas" },
  { name: "Aducao de Quadril na Polia", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/hBGWILP.gif", description: "Adutores na polia" },
  { name: "Elevacao de Pernas deitado", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/WhuFnR7.gif", description: "Reto abdominal inferior" },
  { name: "Elevacao de Pernas na Barra", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/I3tsCnC.gif", description: "Grande ativacao do core" },
  { name: "Elevacao na Cadeira Romana", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/weoDEpH.gif", description: "Elevacao com apoio nos antebracos" },
  { name: "Prancha Lateral", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/RKjH6Lt.gif", description: "Obliquos e core lateral" },
  { name: "Prancha Reversa", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/tFToB7l.gif", description: "Core posterior" },
  { name: "Russian Twist com Peso", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/WU9BLIs.gif", description: "Rotacao com carga" },
  { name: "Russian Twist com Bola", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/d9Xaxq6.gif", description: "Rotacao sobre a bola" },
  { name: "Abdominal em Pe na Polia", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/jpgqxiS.gif", description: "Crunch em pe com tensao" },
  { name: "Abdominal de Joelhos na Polia", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/WW95auq.gif", description: "Crunch de joelhos" },
  { name: "Abdominal Sentado na Polia", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/8xUv4J7.gif", description: "Crunch sentado no cabo" },
  { name: "Pallof Vertical", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/G7PXMlT.gif", description: "Anti-rotacao com elastico" },
  { name: "Elevacao de Quadril deitado", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/196HJGw.gif", description: "Elevacao pelvica deitado" },
  { name: "Obliquo Suspenso na Barra", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/BaE7O6U.gif", description: "Obliquos na barra" },
  { name: "Curl-up", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/g2oKspu.gif", description: "Abdominal espinhal" },
  { name: "Elevacao de Pernas Torcida", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/C0eCeEt.gif", description: "Obliquos com torcao" },
  { name: "Burpee", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/dK9394r.gif", description: "Treino HIIT completo" },
  { name: "Burpee com Halter", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/0JtKWum.gif", description: "Burpee com carga" },
  { name: "Pular Corda", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/e1e76I2.gif", description: "Salto na corda" },
  { name: "Bicicleta Estacionaria", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/a8VDgLw.gif", description: "Ciclismo indoor" },
  { name: "Esteira - Corrida", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/y5p0H8a.gif", description: "Corrida na esteira" },
  { name: "Elíptico", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/rjtuP6X.gif", description: "Cross trainer (elíptico)" },
  { name: "Escada / Stepper", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/j9Q5crt.gif", description: "Subida na escada" },
  { name: "Polichinelo", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/1g5bPpA.gif", description: "Salto com abertura" },
  { name: "Star Jump", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/HtfCpfi.gif", description: "Salto em estrela" },
  { name: "Escalador (Mountain Climber)", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/9c6T1YX.gif", description: "Corrida em prancha" },
  { name: "Salto Tesoura", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/Eh2v5Iu.gif", description: "Salto em tesoura" },
  { name: "Salto Afastado", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/f9lVSSI.gif", description: "Salto com pernas afastadas" },
  { name: "Passada de Esqui", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/5MRH8H2.gif", description: "Simulacao de esqui" },
  { name: "Corrida Explosiva", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/PrQbjvB.gif", description: "Impulso e corrida" },
  { name: "Alongamento do Corredor", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/0mB6wHO.gif", description: "Posterior e quadril" },
  { name: "Alongamento de Posterior", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/yRYyfdA.gif", description: "Isquiotibiais" },
  { name: "Alongamento de Panturrilha na Parede", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/m0tCHqc.gif", description: "Gastrocnemio" },
  { name: "Alongamento de Quadriceps", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/YUYAMEj.gif", description: "Quadriceps deitado" },
  { name: "Alongamento de Gluteo Sentado", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/DeDThfG.gif", description: "Gluteo e rotadores" },
  { name: "Alongamento de Flexor do Quadril", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/2LQkNPW.gif", description: "Flexor do quadril com bola" },
  { name: "Alongamento Lateral do Pescoço", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/x2chWLO.gif", description: "Trapezio e pescoço" },
  { name: "Alongamento de Peito", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/QoHIhPl.gif", description: "Peitoral em pe" },
  { name: "Alongamento Lombar", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/yU7w7CA.gif", description: "Lombar com bola" },
  { name: "Iron Cross Stretch", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/pZwUsKB.gif", description: "Mobilidade toracica" },
  { name: "Postura da Borboleta (Yoga)", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/bWlZvXh.gif", description: "Quadril em yoga" },
  { name: "Alongamento do Sapo", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/2Dk4xQV.gif", description: "Mobilidade de quadril" },
  { name: "Alongamento de Triceps", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/Z5YStHW.gif", description: "Triceps acima da cabeca" },
  { name: "Alongamento de Ombro Posterior", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/xifhB5W.gif", description: "Deltoide posterior" },
  { name: "Alongamento de Posterior deitado", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/sU5BrfP.gif", description: "Isquiotibiais deitado" },
  { name: "Alongamento Lateral de Quadriceps", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/BWnJR72.gif", description: "Quadriceps lateral" },
  { name: "Alongamento Dinamico de Peito", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/3uj0Ozg.gif", description: "Peito dinamico" },
  { name: "Alongamento de Coxa na Cadeira", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/xGgAGPm.gif", description: "Coxa e posterior" },
  { name: "Rosca de Punho com Barra", muscleGroup: "Outros", gifUrl: "https://static.exercisedb.dev/media/82LxxkW.gif", description: "Flexores do punho" },
  { name: "Rosca de Punho Inversa", muscleGroup: "Outros", gifUrl: "https://static.exercisedb.dev/media/LsZkfU6.gif", description: "Extensores do punho" },
  { name: "Punho na Polia", muscleGroup: "Outros", gifUrl: "https://static.exercisedb.dev/media/LrV4s90.gif", description: "Flexores com cabo" },
  { name: "Punho Inverso com Halter", muscleGroup: "Outros", gifUrl: "https://static.exercisedb.dev/media/BLCvwr2.gif", description: "Extensores com halter" },
  { name: "Flexao dos Dedos", muscleGroup: "Outros", gifUrl: "https://static.exercisedb.dev/media/mtXengz.gif", description: "Musculatura flexora dos dedos" },
  { name: "Supino Declinado no Cabo", muscleGroup: "Peito", gifUrl: "https://static.exercisedb.dev/media/2Pya1cP.gif", description: "Press de peito inferior no cabo" },
  { name: "Remada Inclinada com Barra", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/dmgMp3n.gif", description: "Remada na base inclinada" },
  { name: "Remada Unilateral com Barra", muscleGroup: "Costas", gifUrl: "https://static.exercisedb.dev/media/Jsgsc27.gif", description: "Trabalho unilateral de dorsal" },
  { name: "Desenvolvimento Sentado com Barra", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/kTbSH9h.gif", description: "Press sentado com barra" },
  { name: "Elevacao Lateral na Polia", muscleGroup: "Ombros", gifUrl: "https://static.exercisedb.dev/media/goJ6ezq.gif", description: "Deltoide lateral no cabo" },
  { name: "Rosca Drag", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/IENzBdA.gif", description: "Curl proximo ao corpo" },
  { name: "Rosca acima da Cabeça no Cabo", muscleGroup: "Bracos", gifUrl: "https://static.exercisedb.dev/media/wDUqY2u.gif", description: "Curl com cabo acima" },
  { name: "Terra com Pernas Rigidas", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/oom75KC.gif", description: "Posterior com pernas esticadas" },
  { name: "Pull Through no Cabo", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/OM46QHm.gif", description: "Gluteos na polia" },
  { name: "Step-up com Elastico", muscleGroup: "Pernas", gifUrl: "https://static.exercisedb.dev/media/d5bTEPV.gif", description: "Subida com resistencia" },
  { name: "Elevacao de Joelhos Assistida", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/03lzqwk.gif", description: "Core suspenso assistido" },
  { name: "Abdominal Lateral na Polia", muscleGroup: "Abdomen", gifUrl: "https://static.exercisedb.dev/media/wPypxFY.gif", description: "Obliquos na polia" },
  { name: "Cross Trainer Ciclo", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/XSCHmiI.gif", description: "Aparelho eliptico de ciclo" },
  { name: "Passada Ida e Volta", muscleGroup: "Cardio", gifUrl: "https://static.exercisedb.dev/media/fNGumX0.gif", description: "Deslocamento lateral" },
  { name: "Alongamento de Panturrilha Sentado", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/17bqEXD.gif", description: "Panturrilha sentado" },
  { name: "Alongamento de Quadril e Quadriceps", muscleGroup: "Mobilidade", gifUrl: "https://static.exercisedb.dev/media/tFGKm99.gif", description: "Flexor do quadril em pe" },
  { name: "Punho Inversa na Polia", muscleGroup: "Outros", gifUrl: "https://static.exercisedb.dev/media/eYmsEPR.gif", description: "Extensores no cabo" },
];
